// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChartExample = "chart_example"

// ChartExample 示例图表表
type ChartExample struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement;comment:ID" json:"id"`                          // ID
	Goal       string    `gorm:"column:goal;type:text;comment:分析目标" json:"goal"`                                  // 分析目标
	Name       string    `gorm:"column:name;type:varchar(128);comment:图表名称" json:"name"`                          // 图表名称
	ChartType  string    `gorm:"column:chartType;type:varchar(32);comment:图表类型" json:"chartType"`                // 图表类型
	GenChart   string    `gorm:"column:genChart;type:text;comment:生成的图表数据" json:"genChart"`                    // 生成的图表数据
	GenResult  string    `gorm:"column:genResult;type:text;comment:生成的分析结论" json:"genResult"`                  // 生成的分析结论
	Status     string    `gorm:"column:status;type:varchar(16);not null;default:wait;comment:状态" json:"status"` // 状态：wait,running,succeed,failed
	CreateTime time.Time `gorm:"column:createTime;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime time.Time `gorm:"column:updateTime;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	IsDelete   int8      `gorm:"column:isDelete;type:tinyint;not null;default:0;comment:是否删除" json:"isDelete"`    // 是否删除
}

// TableName ChartExample's table name
func (*ChartExample) TableName() string {
	return TableNameChartExample
}
