basePath: /
definitions:
  api.CurrentUserDetailResp:
    properties:
      message:
        description: |-
          required: true
          example: 登陆成功
        type: string
      statusCode:
        description: |-
          required: true
          example: 0
        type: integer
      userInfoV0:
        $ref: '#/definitions/api.UserInfoV0'
    type: object
  api.GenChartResp:
    properties:
      genChart:
        type: string
      genResult:
        type: string
      message:
        type: string
      statusCode:
        type: integer
    type: object
  api.UserInfoV0:
    properties:
      createTime:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      updateTime:
        description: 更新时间
        type: string
      userAccount:
        description: 账号
        type: string
      userAvatar:
        description: 用户头像
        type: string
      userName:
        description: 用户昵称
        type: string
      userRole:
        description: 用户角色：user/admin
        type: string
    type: object
  api.UserLoginReq:
    properties:
      account:
        type: string
      password:
        type: string
    required:
    - account
    - password
    type: object
  api.UserLoginResp:
    properties:
      message:
        type: string
      statusCode:
        type: integer
      token:
        type: string
    type: object
  api.UserRegisterReq:
    properties:
      account:
        type: string
      password:
        type: string
    required:
    - account
    - password
    type: object
  api.UserRegisterResp:
    properties:
      message:
        description: |-
          required: true
          example: 登陆成功
        type: string
      statusCode:
        description: |-
          required: true
          example: 0
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: txnbi 的 API
  title: txnbi API
  version: "1.0"
paths:
  /chart/gen:
    post:
      description: AI生成图表数据接口
      parameters:
      - description: 用户token
        in: formData
        name: token
        required: true
        type: string
      - description: 表名
        in: formData
        name: chartName
        required: true
        type: string
      - description: 表类型
        in: formData
        name: chartType
        required: true
        type: string
      - description: 查询目标
        in: formData
        name: goal
        required: true
        type: string
      - description: 用户上传的文件
        in: formData
        name: chartData
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GenChartResp'
      summary: AI生成图表数据接口
      tags:
      - chart
  /user/CurrentUserDetail:
    get:
      description: 用户自身详情接口
      parameters:
      - in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CurrentUserDetailResp'
      summary: 用户自身详情接口
      tags:
      - user
  /user/login:
    post:
      description: 登陆界面中的用户登陆接口
      parameters:
      - description: 登陆信息
        in: body
        name: LoginInfo
        required: true
        schema:
          $ref: '#/definitions/api.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserLoginResp'
      summary: 用户登陆接口
      tags:
      - user
  /user/register:
    post:
      description: 登陆界面中的用户注册接口
      parameters:
      - description: 注册信息
        in: body
        name: RegisterInfo
        required: true
        schema:
          $ref: '#/definitions/api.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserRegisterResp'
      summary: 用户注册接口
      tags:
      - user
swagger: "2.0"
